#!/usr/bin/env python3
"""Minimal Markdown <-> HTML conversion for artifact_sync (stdlib only).

The kit is stdlib-only (no `markdown`, no `html2text`), so both directions are
hand-rolled and DELIBERATELY LIMITED. Neither is a general-purpose converter
and neither is round-trip safe:

  md_to_html()  renders a documented CommonMark subset. Anything outside the
                subset is emitted as escaped text rather than guessed at.
  html_to_md()  extracts a READABLE DIGEST (headings, paragraphs, list items,
                links, code) via html.parser. It is lossy by construction —
                layout, styling and scripted content cannot survive.

Both are used only to generate the COUNTERPART of an artifact's source file.
The source is always stored verbatim and is the file a human edits; generated
files carry a banner saying so. See docs/ARCHITECTURE.md.

`_`-prefixed so the daemon's `engine/hooks/*.py` glob does not mistake this
helper for a hook module.
"""
import html
import re
from html.parser import HTMLParser

GENERATED_HTML_BANNER = (
    "<!-- GENERATED by ecosystem-kit artifact_sync from {source} — do not edit. "
    "Edit the source and republish. -->"
)
GENERATED_MD_BANNER = (
    "<!-- GENERATED by ecosystem-kit artifact_sync from {source} — do not edit. "
    "This is a lossy text digest, not the artifact. Edit the source and republish. -->"
)


# ───────────────────────── Markdown -> HTML ─────────────────────────

_INLINE_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"(?<![*\w])\*([^*\n]+)\*(?!\*)")
_LINK = re.compile(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
_IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
_HR = re.compile(r"^\s{0,3}(?:-{3,}|\*{3,}|_{3,})\s*$")
_ATX = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_UL = re.compile(r"^\s{0,3}[-*+]\s+(.*)$")
_OL = re.compile(r"^\s{0,3}(\d+)[.)]\s+(.*)$")
_QUOTE = re.compile(r"^\s{0,3}>\s?(.*)$")
_FENCE = re.compile(r"^\s{0,3}(`{3,}|~{3,})\s*([A-Za-z0-9_+-]*)\s*$")
_TABLE_DELIM = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$")


def _safe_url(url: str) -> str:
    """Allow only benign URL schemes; `javascript:` and `data:` are dropped."""
    lowered = url.strip().lower()
    if lowered.startswith(("javascript:", "data:", "vbscript:")):
        return "#"
    return html.escape(url.strip(), quote=True)


def _inline(text: str) -> str:
    """Escape, then re-introduce the inline constructs we support."""
    placeholders = []

    def stash(rendered: str) -> str:
        placeholders.append(rendered)
        return "\x00%d\x00" % (len(placeholders) - 1)

    def do_image(m):
        return stash('<img src="%s" alt="%s">' % (_safe_url(m.group(2)), html.escape(m.group(1))))

    def do_link(m):
        return stash('<a href="%s">%s</a>' % (_safe_url(m.group(2)), _inline_no_links(m.group(1))))

    def do_code(m):
        return stash("<code>%s</code>" % html.escape(m.group(1)))

    text = _IMAGE.sub(do_image, text)
    text = _LINK.sub(do_link, text)
    text = _INLINE_CODE.sub(do_code, text)
    text = html.escape(text)
    text = _BOLD.sub(lambda m: "<strong>%s</strong>" % m.group(1), text)
    text = _ITALIC.sub(lambda m: "<em>%s</em>" % m.group(1), text)

    return re.sub(r"\x00(\d+)\x00", lambda m: placeholders[int(m.group(1))], text)


def _inline_no_links(text: str) -> str:
    """Inline rendering for link labels — no nested links."""
    text = _INLINE_CODE.sub(lambda m: "\x01%s\x01" % html.escape(m.group(1)), text)
    text = html.escape(text)
    text = _BOLD.sub(lambda m: "<strong>%s</strong>" % m.group(1), text)
    text = _ITALIC.sub(lambda m: "<em>%s</em>" % m.group(1), text)
    return text.replace("\x01", "").strip() or "link"


def _split_row(line: str) -> list:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [c.strip() for c in line.split("|")]


def md_to_html(md_text: str) -> str:
    """Render a documented Markdown subset to an HTML fragment.

    Supported: ATX headings, fenced code, paragraphs, unordered/ordered lists,
    blockquotes, horizontal rules, GFM pipe tables, and the inline set
    (code, bold, italic, links, images). Everything else is escaped text.
    """
    lines = md_text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    out = []
    i = 0
    n = len(lines)

    while i < n:
        line = lines[i]

        fence = _FENCE.match(line)
        if fence:
            marker = fence.group(1)[0]
            lang = fence.group(2)
            body = []
            i += 1
            while i < n:
                close = _FENCE.match(lines[i])
                if close and close.group(1)[0] == marker:
                    i += 1
                    break
                body.append(lines[i])
                i += 1
            cls = ' class="language-%s"' % html.escape(lang) if lang else ""
            out.append("<pre><code%s>%s</code></pre>" % (cls, html.escape("\n".join(body))))
            continue

        if not line.strip():
            i += 1
            continue

        if _HR.match(line):
            out.append("<hr>")
            i += 1
            continue

        atx = _ATX.match(line)
        if atx:
            level = len(atx.group(1))
            out.append("<h%d>%s</h%d>" % (level, _inline(atx.group(2)), level))
            i += 1
            continue

        # GFM table: a header row followed by a delimiter row.
        if "|" in line and i + 1 < n and _TABLE_DELIM.match(lines[i + 1]):
            headers = _split_row(line)
            i += 2
            rows = []
            while i < n and lines[i].strip() and "|" in lines[i]:
                rows.append(_split_row(lines[i]))
                i += 1
            thead = "".join("<th>%s</th>" % _inline(h) for h in headers)
            tbody = "".join(
                "<tr>%s</tr>" % "".join("<td>%s</td>" % _inline(c) for c in r)
                for r in rows
            )
            out.append(
                '<div class="table-scroll"><table><thead><tr>%s</tr></thead>'
                "<tbody>%s</tbody></table></div>" % (thead, tbody)
            )
            continue

        if _QUOTE.match(line):
            body = []
            while i < n and _QUOTE.match(lines[i]):
                body.append(_QUOTE.match(lines[i]).group(1))
                i += 1
            out.append("<blockquote>%s</blockquote>" % md_to_html("\n".join(body)))
            continue

        if _UL.match(line) or _OL.match(line):
            ordered = bool(_OL.match(line))
            items = []
            while i < n:
                m = _OL.match(lines[i]) if ordered else _UL.match(lines[i])
                if not m:
                    break
                items.append(m.group(2) if ordered else m.group(1))
                i += 1
            tag = "ol" if ordered else "ul"
            out.append(
                "<%s>%s</%s>" % (tag, "".join("<li>%s</li>" % _inline(it) for it in items), tag)
            )
            continue

        para = []
        while i < n and lines[i].strip() and not (
            _ATX.match(lines[i]) or _HR.match(lines[i]) or _FENCE.match(lines[i])
            or _UL.match(lines[i]) or _OL.match(lines[i]) or _QUOTE.match(lines[i])
        ):
            para.append(lines[i].strip())
            i += 1
        if para:
            out.append("<p>%s</p>" % _inline(" ".join(para)))

    return "\n".join(out)


# Minimal, theme-aware shell for a generated HTML page. Deliberately plain:
# the generated file exists to be readable in a browser and diffable in git,
# not to reproduce the published artifact's design.
_HTML_SHELL = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
{banner}
<style>
  :root {{ color-scheme: light dark; --bg:#ffffff; --fg:#1a1d23; --muted:#5d6470;
           --rule:#e2e5ea; --code-bg:#f2f4f7; --link:#0b5fbd; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#12151a; --fg:#e6e9ee; --muted:#98a1ae; --rule:#282e38;
             --code-bg:#1c212a; --link:#7ab3f5; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--fg); line-height:1.65;
          font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; }}
  main {{ max-width: 46rem; margin:0 auto; padding: 2.5rem 1.25rem 5rem; }}
  h1,h2,h3,h4,h5,h6 {{ line-height:1.25; margin:2rem 0 .75rem; text-wrap:balance; }}
  h1 {{ margin-top:0; }}
  p, ul, ol, blockquote {{ margin: 0 0 1rem; }}
  a {{ color: var(--link); }}
  code {{ background:var(--code-bg); padding:.1em .35em; border-radius:3px;
          font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size:.9em; }}
  pre {{ background:var(--code-bg); padding:1rem; overflow-x:auto; border-radius:4px; }}
  pre code {{ background:none; padding:0; }}
  blockquote {{ border-left:3px solid var(--rule); margin-left:0; padding-left:1rem; color:var(--muted); }}
  hr {{ border:none; border-top:1px solid var(--rule); margin:2rem 0; }}
  .table-scroll {{ overflow-x:auto; margin:0 0 1rem; }}
  table {{ border-collapse:collapse; width:100%; font-size:.94em; }}
  th, td {{ border:1px solid var(--rule); padding:.45rem .7rem; text-align:left; }}
  th {{ background:var(--code-bg); }}
  img {{ max-width:100%; height:auto; }}
  .kit-meta {{ color:var(--muted); font-size:.85rem; border-bottom:1px solid var(--rule);
               padding-bottom:1rem; margin-bottom:2rem; }}
</style>
</head>
<body>
<main>
<p class="kit-meta">{meta}</p>
{body}
</main>
</body>
</html>
"""


def md_file_to_html_page(md_text: str, title: str, source_name: str, meta_html: str) -> str:
    """Wrap md_to_html output in a standalone, theme-aware HTML page."""
    return _HTML_SHELL.format(
        title=html.escape(title or source_name),
        banner=GENERATED_HTML_BANNER.format(source=html.escape(source_name)),
        meta=meta_html,
        body=md_to_html(md_text),
    )


# ───────────────────────── HTML -> Markdown digest ─────────────────────────

# NOTE: `head` is deliberately NOT here. Skipping it swallowed <title> before
# handle_starttag could reach the title branch, so every digest came back
# titleless. The tags that actually carry noise inside <head> (script, style)
# are skipped on their own account; <meta>/<link> are void and emit no data.
_SKIP_TAGS = {"script", "style", "noscript", "template", "svg"}
_BLOCK_TAGS = {
    "p", "div", "section", "article", "header", "footer", "main", "aside",
    "tr", "br", "blockquote", "pre", "figcaption", "dd", "dt",
}


class _DigestParser(HTMLParser):
    """Collect a readable text digest from an HTML document.

    Headings become Markdown headings, list items become bullets, links are
    kept inline as [text](href), and everything inside _SKIP_TAGS is dropped.
    """

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []
        self._skip_depth = 0
        self._heading = None
        self._buf = []
        self._list_depth = 0
        self._in_li = False
        self._href = None
        self.title = None
        self._in_title = False

    # -- helpers
    def _flush(self):
        text = re.sub(r"[ \t]+", " ", "".join(self._buf)).strip()
        self._buf = []
        if not text:
            return
        if self._heading:
            self.parts.append("%s %s" % ("#" * self._heading, text))
        elif self._in_li:
            self.parts.append("- %s" % text)
        else:
            self.parts.append(text)

    def handle_starttag(self, tag, attrs):
        if self._skip_depth:
            if tag in _SKIP_TAGS:
                self._skip_depth += 1
            return
        if tag in _SKIP_TAGS:
            self._skip_depth = 1
            return
        if tag == "title":
            self._in_title = True
            return
        if tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self._flush()
            self._heading = int(tag[1])
            return
        if tag == "li":
            self._flush()
            self._in_li = True
            return
        if tag in ("ul", "ol"):
            self._flush()
            self._list_depth += 1
            return
        if tag == "a":
            self._href = dict(attrs).get("href")
            return
        if tag == "hr":
            self._flush()
            self.parts.append("---")
            return
        if tag in _BLOCK_TAGS:
            self._flush()

    def handle_endtag(self, tag):
        if self._skip_depth:
            if tag in _SKIP_TAGS:
                self._skip_depth -= 1
            return
        if tag == "title":
            self._in_title = False
            self.title = re.sub(r"\s+", " ", "".join(self._buf)).strip() or None
            self._buf = []
            return
        if tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self._flush()
            self._heading = None
            return
        if tag == "li":
            self._flush()
            self._in_li = False
            return
        if tag in ("ul", "ol"):
            self._flush()
            self._list_depth = max(0, self._list_depth - 1)
            return
        if tag == "a":
            self._href = None
            return
        if tag in _BLOCK_TAGS:
            self._flush()

    def handle_data(self, data):
        if self._skip_depth:
            return
        if self._in_title:
            self._buf.append(data)
            return
        if not data.strip():
            self._buf.append(" ")
            return
        if self._href and not self._href.startswith("#"):
            self._buf.append("[%s](%s)" % (data.strip(), self._href))
        else:
            self._buf.append(data)

    def close(self):
        super().close()
        self._flush()


def html_to_md(html_text: str) -> tuple:
    """Return (title, markdown_digest). Lossy by construction — see module doc."""
    parser = _DigestParser()
    try:
        parser.feed(html_text)
        parser.close()
    except Exception:
        # html.parser can raise on pathological input; a partial digest still
        # beats losing the record entirely.
        pass

    blocks = []
    for part in parser.parts:
        if blocks and blocks[-1] == part:
            continue
        blocks.append(part)

    return parser.title, "\n\n".join(blocks).strip()
