#!/usr/bin/env python3
"""
PostToolUse:Artifact — mirror every published artifact into the repo.

Artifacts are authored in the session scratchpad (`/tmp/.../scratchpad/`),
which is wiped when the session ends. Publishing therefore produced a live URL
and NOTHING on disk: 37 publishes across two artifacts left zero files behind
(observed 2026-08-27). This hook mirrors each publish into the repo so the
artifact is versioned, diffable, reviewable in a PR, and editable in place.

Layout (``artifacts.dir``, default ``docs/artifacts``)::

    docs/artifacts/<slug>/<slug>.<ext>   source, verbatim — the file a human edits
    docs/artifacts/<slug>/<slug>.<alt>   generated counterpart, banner-marked
    docs/artifacts/<slug>/artifact.json  id, url, title, description, version
    docs/artifacts/INDEX.md              one row per artifact

Both representations are kept because they do different jobs: the HTML is what
you open in a browser, the Markdown is what reads and diffs in a PR. Only one
of the pair is authoritative — whichever format was published. The other is
generated by ``_markdown`` and carries a "do not edit" banner, because the kit
is stdlib-only and neither conversion direction is faithful (md->html renders a
documented subset; html->md is a lossy text digest).

Idempotency is keyed on ``tool_response.artifact_id``, which is stable across
republishes — filename is not (the same artifact republishes from the same temp
path, and a retitled artifact changes slug). A directory whose artifact.json
carries the id is reused and rewritten in place, so N republishes yield one
directory, not N.

Advisory only — always exits 0. A failure here must never block a publish.
"""
import json
import os
import re
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from _constants import PROJECT_ROOT, load_kit
from _markdown import (
    GENERATED_MD_BANNER,
    html_to_md,
    md_file_to_html_page,
)

INDEX_NAME = "INDEX.md"
META_NAME = "artifact.json"
MAX_SLUG = 60
GIT_TIMEOUT = 20

# Actions the Artifact tool accepts that are NOT a publish. A comment read or
# an asset upload must not create a directory.
NON_PUBLISH_ACTIONS = {
    "list", "comments", "reply", "resolve",
    "upload_asset", "list_assets", "read_asset", "delete_asset",
}


def cfg() -> dict:
    conf = load_kit().get("artifacts") or {}
    return {
        "enabled": conf.get("enabled", True),
        "dir": conf.get("dir") or "docs/artifacts",
        "commit": conf.get("commit", True),
        "commit_type": conf.get("commit_type") or "docs",
    }


def slugify(text: str, fallback: str = "artifact") -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)[:MAX_SLUG].strip("-")
    return slug or fallback


def find_existing(root: str, artifact_id: str):
    """Return the directory already holding this artifact id, if any."""
    if not artifact_id or not os.path.isdir(root):
        return None
    try:
        entries = sorted(os.listdir(root))
    except OSError:
        return None
    for name in entries:
        meta_path = os.path.join(root, name, META_NAME)
        if not os.path.isfile(meta_path):
            continue
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                if json.load(f).get("artifact_id") == artifact_id:
                    return os.path.join(root, name)
        except (OSError, ValueError):
            continue
    return None


def unique_dir(root: str, slug: str, artifact_id: str) -> str:
    """A fresh directory for `slug`, disambiguated if the name is taken."""
    candidate = os.path.join(root, slug)
    if not os.path.exists(candidate):
        return candidate
    return os.path.join(root, "%s-%s" % (slug, (artifact_id or "x")[:8]))


def read_text(path: str):
    for encoding in ("utf-8", "utf-8-sig", "latin-1"):
        try:
            with open(path, "r", encoding=encoding) as f:
                return f.read()
        except UnicodeDecodeError:
            continue
        except OSError:
            return None
    return None


def write_text(path: str, text: str) -> bool:
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        return True
    except OSError:
        return False


def meta_line_html(meta: dict) -> str:
    url = meta.get("url") or ""
    bits = []
    if meta.get("title"):
        bits.append("<strong>%s</strong>" % meta["title"])
    if url:
        bits.append('Published at <a href="%s">%s</a>' % (url, url))
    bits.append("Generated from <code>%s</code> by ecosystem-kit." % meta.get("source_file", ""))
    return " &middot; ".join(bits)


def build_index(root: str, rel_dir: str) -> str:
    """Rebuild INDEX.md from the artifact.json files actually on disk."""
    rows = []
    try:
        names = sorted(os.listdir(root))
    except OSError:
        names = []
    for name in names:
        meta_path = os.path.join(root, name, META_NAME)
        if not os.path.isfile(meta_path):
            continue
        try:
            with open(meta_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
        except (OSError, ValueError):
            continue
        title = str(meta.get("title") or name).replace("|", "\\|")
        desc = str(meta.get("description") or "").replace("|", "\\|")
        if len(desc) > 90:
            desc = desc[:87] + "..."
        url = meta.get("url") or ""
        src = meta.get("source_file") or ""
        rows.append(
            "| [%s](%s/%s) | %s | %s | [open](%s) |"
            % (title, name, src, desc, meta.get("updated_at", ""), url)
        )

    header = [
        "# Published artifacts",
        "",
        "Mirrored automatically by the ecosystem-kit `artifact_sync` hook on every",
        "publish. Each directory holds the **source file** (edit this one), a",
        "**generated counterpart** in the other format, and `artifact.json`.",
        "",
        "To change an artifact: edit its source file here, then republish it with its",
        "URL so the live page and this copy stay in step.",
        "",
        "| Artifact | Description | Updated | Live |",
        "| --- | --- | --- | --- |",
    ]
    if not rows:
        rows = ["| _none yet_ | | | |"]
    return "\n".join(header + rows) + "\n"


def git(args, cwd):
    try:
        return subprocess.run(
            ["git"] + args, cwd=cwd, capture_output=True, text=True, timeout=GIT_TIMEOUT
        )
    except (OSError, subprocess.SubprocessError):
        return None


def commit(paths, message, conf):
    """Commit ONLY `paths`. Returns a status string for the report.

    Uses a pathspec commit (`git commit -- <paths>`), which takes those paths
    from the working tree and ignores whatever else is staged — a hook firing
    mid-session must never sweep up unrelated work. Refuses on a protected
    branch and during a merge/rebase; never pushes.
    """
    if not conf["commit"]:
        return "not committed (artifacts.commit is false)"

    inside = git(["rev-parse", "--is-inside-work-tree"], PROJECT_ROOT)
    if not inside or inside.returncode != 0:
        return "not committed (not a git work tree)"

    head = git(["rev-parse", "--abbrev-ref", "HEAD"], PROJECT_ROOT)
    branch = (head.stdout.strip() if head and head.returncode == 0 else "") or ""
    protected = load_kit().get("protected_branches") or []
    if branch in protected:
        return "NOT COMMITTED — on protected branch '%s'; commit it on a branch" % branch
    if branch == "HEAD":
        return "not committed (detached HEAD)"

    git_dir = os.path.join(PROJECT_ROOT, ".git")
    for marker in ("MERGE_HEAD", "rebase-merge", "rebase-apply", "CHERRY_PICK_HEAD"):
        if os.path.exists(os.path.join(git_dir, marker)):
            return "not committed (merge/rebase in progress)"

    status = git(["status", "--porcelain", "--"] + paths, PROJECT_ROOT)
    if status is not None and status.returncode == 0 and not status.stdout.strip():
        return "no change to commit"

    # `git commit -- <paths>` is a partial commit over paths git already KNOWS;
    # on an artifact's first publish every file is untracked and it fails with
    # "pathspec ... did not match any file(s) known to git". Stage the artifact
    # paths explicitly first — still scoped, still ignores the rest of the index.
    added = git(["add", "--"] + paths, PROJECT_ROOT)
    if added is None or added.returncode != 0:
        detail = (added.stderr or "").strip().splitlines() if added else []
        return "commit failed at stage: %s" % (detail[0] if detail else "git add failed")

    result = git(["commit", "-m", message, "--"] + paths, PROJECT_ROOT)
    if result is None:
        return "commit failed (git unavailable)"
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip().splitlines()
        return "commit failed: %s" % (detail[0] if detail else "unknown error")
    return "committed on '%s'" % branch


def main():
    try:
        event = json.loads(sys.stdin.read())
    except Exception:
        sys.exit(0)

    if event.get("tool_name") != "Artifact":
        sys.exit(0)

    tool_input = event.get("tool_input") or {}
    response = event.get("tool_response")
    if not isinstance(response, dict):
        sys.exit(0)

    # Only real publishes produce a URL; list/comments/asset actions do not.
    if str(tool_input.get("action") or "publish") in NON_PUBLISH_ACTIONS:
        sys.exit(0)
    url = response.get("url")
    source_path = response.get("path") or tool_input.get("file_path")
    if not url or not source_path or not os.path.isfile(source_path):
        sys.exit(0)

    conf = cfg()
    if not conf["enabled"]:
        sys.exit(0)

    source_text = read_text(source_path)
    if source_text is None:
        sys.exit(0)

    artifact_id = response.get("artifact_id") or ""
    source_ext = os.path.splitext(source_path)[1].lower()
    is_markdown = source_ext in (".md", ".markdown")
    base = os.path.splitext(os.path.basename(source_path))[0]
    title = response.get("title") or tool_input.get("title") or base

    root = os.path.join(PROJECT_ROOT, conf["dir"])
    target = find_existing(root, artifact_id) or unique_dir(root, slugify(title, base), artifact_id)
    slug = os.path.basename(target)

    src_name = "%s%s" % (slug, ".md" if is_markdown else ".html")
    alt_name = "%s%s" % (slug, ".html" if is_markdown else ".md")

    # A republish usually carries only file_path + label, so description and
    # favicon arrive empty. Overwriting blind would erase them on every update;
    # carry the previous values forward unless this publish supplies new ones.
    prior = {}
    prior_path = os.path.join(target, META_NAME)
    if os.path.isfile(prior_path):
        try:
            with open(prior_path, "r", encoding="utf-8") as f:
                prior = json.load(f)
        except (OSError, ValueError):
            prior = {}
    if not isinstance(prior, dict):
        prior = {}

    meta = {
        "artifact_id": artifact_id,
        "url": url,
        "title": title,
        "description": tool_input.get("description") or prior.get("description") or "",
        "favicon": tool_input.get("favicon") or prior.get("favicon") or "",
        "version": response.get("version") or "",
        "source_file": src_name,
        "generated_file": alt_name,
        "source_format": "markdown" if is_markdown else "html",
        "published_from": source_path,
        "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
    }

    written = []
    if write_text(os.path.join(target, src_name), source_text):
        written.append(src_name)

    if is_markdown:
        page = md_file_to_html_page(source_text, title, src_name, meta_line_html(meta))
        if write_text(os.path.join(target, alt_name), page):
            written.append(alt_name)
    else:
        _, digest = html_to_md(source_text)
        body = [
            GENERATED_MD_BANNER.format(source=src_name),
            "",
            "# %s" % title,
            "",
            "> Lossy text digest of `%s`. The published page is the source of truth:" % src_name,
            "> <%s>" % url,
            "",
            "---",
            "",
            digest or "_No extractable text content._",
            "",
        ]
        if write_text(os.path.join(target, alt_name), "\n".join(body)):
            written.append(alt_name)

    if write_text(os.path.join(target, META_NAME), json.dumps(meta, indent=2) + "\n"):
        written.append(META_NAME)

    index_path = os.path.join(root, INDEX_NAME)
    write_text(index_path, build_index(root, conf["dir"]))

    rel_target = os.path.relpath(target, PROJECT_ROOT).replace(os.sep, "/")
    rel_index = os.path.relpath(index_path, PROJECT_ROOT).replace(os.sep, "/")
    verb = "update" if response.get("updated") else "add"
    status = commit(
        [rel_target, rel_index],
        "%s(artifact): %s %s" % (conf["commit_type"], verb, slug),
        conf,
    )

    lines = [
        "Artifact mirrored into the repo (ecosystem-kit artifact_sync):",
        "  -> %s/ (%s)" % (rel_target, ", ".join(written) or "no files written"),
        "  source of truth: %s — the other file is generated, do not edit it" % src_name,
        "  %s" % status,
    ]
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": "\n".join(lines),
        }
    }))
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        print(f"[ecosystem-kit] artifact_sync: {e}", file=sys.stderr)
        sys.exit(0)
